"""
3474. Lexicographically Smallest Generated String
    You are given two strings, str1 and str2, of lengths n and m, respectively.
    A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

    If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
    Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

    Example :
    Input: str1 = "TFTF", str2 = "ab"

    Output: "ababa"
    Explanation:
    The table below represents the string "ababa"
    Index	T/F	Substring of length m
    0	'T'	"ab"
    1	'F'	"ba"
    2	'T'	"ab"
    3	'F'	"ba"
    The strings "ababa" and "ababb" can be generated by str1 and str2.
    Return "ababa" since it is the lexicographically smaller string.
"""

class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        s1, s2 = len(str1), len(str2)
        arr = ['X'] * (s1 + s2 - 1)
        
        for i in range(s1):
            if str1[i] == 'F':
                continue
            for j in range(s2):
                if arr[i + j] == 'X':
                    arr[i + j] = str2[j]
                elif arr[i + j] != str2[j]:
                    return ""
        
        for i in range(s1):
            if str1[i] == "T":
                continue
            flag = True
            for j in range(s2):
                if arr[i + j] != str2[j]:
                    flag = False
                    break
            if flag:
                return ""

        if arr.count('X') == 0:
            return "".join(arr)

        for i in range(s1):
            if str1[i] == 'F':
                match = True
                last = -1
                for j in range(s2 - 1, -1, -1):
                    if arr[i + j] == 'X':
                        if last == -1:
                            last = i + j
                        if str2[j] != 'a':
                            match = False
                            break
                    else:
                        if arr[i + j] != str2[j]:
                            match = False
                            break
                if match:
                    if last == -1:
                        return ""
                    arr[last] = 'b'

        for i in range(len(arr)):
            if arr[i] == 'X':
                arr[i] = 'a'

        return "".join(arr)