/**
3474. Lexicographically Smallest Generated String
    You are given two strings, str1 and str2, of lengths n and m, respectively.
    A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

    If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
    Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

    Example :
    Input: str1 = "TFTF", str2 = "ab"

    Output: "ababa"
    Explanation:
    The table below represents the string "ababa"
    Index	T/F	Substring of length m
    0	'T'	"ab"
    1	'F'	"ba"
    2	'T'	"ab"
    3	'F'	"ba"
    The strings "ababa" and "ababb" can be generated by str1 and str2.
    Return "ababa" since it is the lexicographically smaller string.
 */



function generateString(str1: string, str2: string): string {
    const s1 = str1.length, s2 = str2.length;
    let arr = new Array(s1 + s2 - 1).fill('X');
    for (let i = 0; i < s1; i++) {
        if (str1[i] === 'F') 
            continue;
        for (let j = 0; j < s2; j++) {
            if (arr[i + j] === 'X') {
                arr[i + j] = str2[j];
            } else if (arr[i + j] !== str2[j]) {
                return "";
            }
        }
    }

    for (let i = 0; i < s1; i++) {
        if (str1[i] === 'T') 
            continue;
        let flag = true;
        for (let j = 0; j < s2; j++) {
            if (arr[i + j] !== str2[j]) {
                flag = false;
                break;
            }
        }
        if (flag) 
            return "";
    }

    if (arr.indexOf('X') === -1) {
        return arr.join('');
    }

    for (let i = 0; i < s1; i++) {
        if (str1[i] === 'F') {
            let match = true;
            let last = -1;
            for (let j = s2 - 1; j >= 0; j--) {
                if (arr[i + j] === 'X') {
                    if (last === -1) last = i + j;
                    if (str2[j] !== 'a') {
                        match = false;
                        break;
                    }
                } else {
                    if (arr[i + j] !== str2[j]) {
                        match = false;
                        break;
                    }
                }
            }
            if (match) {
                if (last === -1) 
                    return "";
                arr[last] = 'b';
            }
        }
    }

    for (let i = 0; i < s1 + s2 - 1; i++) {
        if (arr[i] === 'X') arr[i] = 'a';
    }

    return arr.join('');
};